-- Step 10 Phase B: shopping lists (FR-40 to FR-45b).

-- FR-45b: a position added to pantry via ALREADY_HAVE/PURCHASED carries the shopping list's
-- suggested quantity as an estimate, not a precisely counted one — the user can refine it later.
ALTER TABLE pantry_item ADD COLUMN is_estimated BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE shopping_list (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_shopping_list_user_id ON shopping_list (user_id);

-- FR-42: block distinguishes "definitely need" (from the active suggestion's missing
-- ingredients) from "check, maybe out" (staples, which FR-29 excludes from pantry accounting
-- entirely, so the system genuinely doesn't know whether the user has them).
-- FR-44/FR-45/FR-45a/FR-45b: PENDING is the default, unresolved state — an item left PENDING
-- is never used to infer anything about pantry contents, which is what FR-45a's "unmarked
-- unchecked box implies nothing" amounts to in practice.
-- user_id is denormalized here too (not just reachable via shopping_list_id), matching every
-- other user-owned entity in this codebase (PantryItem, Recipe, CookedDish, RecipeSuggestion,
-- PreferenceSignal) — ownership checks (FR-03) are a direct column filter everywhere, not a
-- join through a parent.
CREATE TABLE shopping_list_item (
    id               BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopping_list_id BIGINT         NOT NULL REFERENCES shopping_list (id) ON DELETE CASCADE,
    user_id          BIGINT         NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    product_id       BIGINT         NOT NULL REFERENCES product (id),
    quantity         NUMERIC(10, 3) NOT NULL,
    unit             VARCHAR(20)    NOT NULL,
    block            VARCHAR(20)    NOT NULL,
    status           VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    resolved_at      TIMESTAMPTZ,

    CONSTRAINT chk_shopping_list_item_quantity_positive CHECK (quantity > 0),
    CONSTRAINT chk_shopping_list_item_unit CHECK (unit IN ('GRAM', 'MILLILITER', 'PIECE')),
    CONSTRAINT chk_shopping_list_item_block CHECK (block IN ('DEFINITELY_NEED', 'CHECK_MAYBE_OUT')),
    CONSTRAINT chk_shopping_list_item_status CHECK (status IN
        ('PENDING', 'PURCHASED', 'ALREADY_HAVE', 'NOT_BUYING', 'NOT_NEEDED'))
);

CREATE INDEX idx_shopping_list_item_shopping_list_id ON shopping_list_item (shopping_list_id);
CREATE INDEX idx_shopping_list_item_user_id ON shopping_list_item (user_id);
