-- Step 12: Telegram account linking (FR-80, FR-80a, FR-80b).

-- FR-80a: hashed, not plaintext, unlike invite_code (V8) — this code proves an existing
-- identity (the authenticated web session that generated it), invite_code doesn't. SHA-256 hex
-- digest (64 hex chars), not BCrypt: this is a high-entropy, randomly generated token, not a
-- low-entropy user-chosen secret — a fast deterministic hash supports an indexed
-- `WHERE code_hash = ?` lookup, which BCrypt's non-deterministic salting cannot.
CREATE TABLE telegram_link_code (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    code_hash   VARCHAR(64) NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    used_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_telegram_link_code_hash UNIQUE (code_hash)
);

-- FR-80b: linked to the numeric Telegram user id, never the (mutable) username.
-- One link per app user and one per Telegram user — prevents either side fanning out to
-- multiple accounts. ON DELETE CASCADE from app_user matches the V8 precedent (FR-05).
CREATE TABLE telegram_link (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    telegram_user_id BIGINT      NOT NULL,
    linked_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_telegram_link_user_id UNIQUE (user_id),
    CONSTRAINT uq_telegram_link_telegram_user_id UNIQUE (telegram_user_id)
);
