-- Step 12: day/meal status (FR-50, FR-50a, INV-13).
CREATE TABLE meal_entry (
    id             BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT         NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    type           VARCHAR(20)    NOT NULL,
    -- cooked_dish rows are never hard-deleted (only status changes), so this FK only ever fires
    -- via the app_user cascade path — CASCADE kept here anyway for correctness.
    cooked_dish_id BIGINT         REFERENCES cooked_dish (id) ON DELETE CASCADE,
    portions_eaten NUMERIC(10, 3),
    kcal           NUMERIC(10, 2),
    protein_grams  NUMERIC(10, 2),
    fat_grams      NUMERIC(10, 2),
    carbs_grams    NUMERIC(10, 2),
    occurred_at    TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT chk_meal_entry_type CHECK (type IN ('COOKED_DISH', 'OUTSIDE', 'GUEST', 'SKIPPED')),
    -- INV-13, enforced at the DB level too (defense in depth beyond MealEntryService's 400):
    -- COOKED_DISH always references a dish + portions; every other type never does.
    CONSTRAINT chk_meal_entry_cooked_dish_consistency CHECK (
        (type = 'COOKED_DISH' AND cooked_dish_id IS NOT NULL AND portions_eaten IS NOT NULL)
        OR (type <> 'COOKED_DISH' AND cooked_dish_id IS NULL)
    )
);

CREATE INDEX idx_meal_entry_user_id ON meal_entry (user_id);
