-- Step 12: dedup for periodic notifications (FR-81 types 2/3).
-- No UNIQUE(user_id, type, reference_id): Postgres treats every NULL as distinct in a unique
-- index, so it would silently fail to dedup SHOPPING_REMINDER rows (reference_id is always NULL
-- there) while working for SPOILAGE. Dedup logic lives in the repository/service instead: an
-- existence check by reference_id for SPOILAGE, a most-recent-timestamp cooldown check for
-- SHOPPING_REMINDER.
CREATE TABLE telegram_notification_log (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    type         VARCHAR(20) NOT NULL,
    reference_id BIGINT,
    sent_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_telegram_notification_log_type CHECK (type IN ('NEW_SUGGESTION', 'SPOILAGE', 'SHOPPING_REMINDER'))
);

CREATE INDEX idx_telegram_notification_log_user_type ON telegram_notification_log (user_id, type, sent_at);
