-- user_profile (PRD section 6, FR-10 to FR-15, FR-70/71/71a/74): the real entity
-- recipe.UserConstraints has stood in for since step 5 ("Stand-in for the real user_profile
-- entity, which doesn't exist yet"). Populated by the onboarding agent scenario (a later step).

CREATE TABLE user_profile (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                         BIGINT      NOT NULL UNIQUE REFERENCES app_user (id) ON DELETE CASCADE,

    -- FR-11 mandatory
    household_size                  INTEGER     NOT NULL,
    max_cook_time_weekday_minutes   INTEGER     NOT NULL,

    -- FR-12 optional. weekly_budget is stored but unconsumed for now: FR-75 (the anti-waste
    -- metric that would use it) is out of scope for this step — no price/cost concept exists
    -- anywhere in this schema yet, so no placeholder calculation is built against this column.
    goal                            VARCHAR(20),
    weekly_budget                   NUMERIC(8, 2),
    preferred_stores                VARCHAR(300),
    country                         VARCHAR(2),

    -- FR-13 TDEE inputs. All nullable — gate block "Б" (goals) only, never block onboarding
    -- completion itself (FR-13: declining these just leaves goals disabled).
    sex                             VARCHAR(10),
    age_years                       INTEGER,
    height_cm                       NUMERIC(5, 1),
    weight_kg                       NUMERIC(5, 1),
    activity_level                  VARCHAR(20),

    goals_enabled                   BOOLEAN     NOT NULL DEFAULT FALSE, -- FR-74

    created_at                      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_user_profile_goal CHECK (goal IN ('LOSE_WEIGHT', 'GAIN_WEIGHT', 'MAINTAIN', 'VARIETY')),
    CONSTRAINT chk_user_profile_sex CHECK (sex IN ('MALE', 'FEMALE')),
    CONSTRAINT chk_user_profile_activity_level CHECK (activity_level IN
        ('SEDENTARY', 'LIGHT', 'MODERATE', 'ACTIVE', 'VERY_ACTIVE')),
    CONSTRAINT chk_user_profile_household_size_positive CHECK (household_size > 0),
    CONSTRAINT chk_user_profile_cook_time_positive CHECK (max_cook_time_weekday_minutes > 0)
);

-- FR-11/FR-14: allergies and dislikes, both absolute vetoes at this layer — same treatment
-- UserConstraints.excludedProductIds already documents ("the distinction only matters for the
-- soft-preference system, not here"). Same @ElementCollection join-table shape as product_synonym.
CREATE TABLE user_profile_excluded_product (
    user_profile_id BIGINT NOT NULL REFERENCES user_profile (id) ON DELETE CASCADE,
    product_id      BIGINT NOT NULL REFERENCES product (id),
    PRIMARY KEY (user_profile_id, product_id)
);

CREATE TABLE user_profile_equipment (
    user_profile_id BIGINT       NOT NULL REFERENCES user_profile (id) ON DELETE CASCADE,
    equipment_name  VARCHAR(100) NOT NULL,
    PRIMARY KEY (user_profile_id, equipment_name)
);

-- FR-12 free days. Stored now; FR-35 (skip meal-plan generation on free days) is NOT wired into
-- the meal-planning scenario in this step — a flagged gap, not a silent drop.
CREATE TABLE user_profile_free_day (
    user_profile_id BIGINT      NOT NULL REFERENCES user_profile (id) ON DELETE CASCADE,
    day_of_week     VARCHAR(10) NOT NULL,
    PRIMARY KEY (user_profile_id, day_of_week),
    CONSTRAINT chk_user_profile_free_day_value CHECK (day_of_week IN
        ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'))
);

CREATE INDEX idx_user_profile_user_id ON user_profile (user_id);
