-- FR-10a/FR-10b: onboarding is the one scenario whose conversation must survive a lost
-- connection or closed tab, so (unlike every other chat scenario, which is stateless per call)
-- the backend itself persists a draft profile and the last few turns. Resolves the PRD's own
-- open question #6 ("separate table or JSONB field?") as a dedicated table with plain TEXT
-- columns holding Jackson-serialized JSON — nothing needs to query *inside* the draft in SQL,
-- the app always loads and deserializes the whole row, so jsonb's only real benefit (in-DB
-- querying) goes unused, and TEXT avoids a new Hibernate type-mapping dependency.
CREATE TABLE onboarding_draft (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL UNIQUE REFERENCES app_user (id) ON DELETE CASCADE,
    draft_json        TEXT        NOT NULL DEFAULT '{}',
    recent_turns_json TEXT        NOT NULL DEFAULT '[]',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- New scenario (PRD 9.1's onboarding step), alongside the existing three from steps 6/7/10.
-- This constraint has been forgotten once before (SHOPPING_LIST, fixed in V11) — don't repeat
-- that here; AgentRunRepositoryTest's @EnumSource(AgentScenario.class) test fails the build if
-- a scenario enum value and this list ever drift apart again.
ALTER TABLE agent_run DROP CONSTRAINT chk_agent_run_scenario;
ALTER TABLE agent_run ADD CONSTRAINT chk_agent_run_scenario CHECK (scenario IN
    ('PANTRY_ASSISTANT', 'MEAL_PLANNING', 'SHOPPING_LIST', 'ONBOARDING'));
