-- Product reference table (FR-43a-d, AI-04a/AI-05, section 6).
-- Canonical name is the cross-system key (English); localized display names are a future resources concern.
CREATE TABLE product (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name        VARCHAR(150)   NOT NULL,
    category              VARCHAR(20)    NOT NULL,
    kcal_per_100g         NUMERIC(7, 2),
    protein_per_100g      NUMERIC(6, 2),
    fat_per_100g          NUMERIC(6, 2),
    carbs_per_100g        NUMERIC(6, 2),
    default_shelf_life_days INTEGER      NOT NULL,
    grams_per_piece       NUMERIC(7, 2),
    is_staple             BOOLEAN        NOT NULL DEFAULT FALSE,
    is_verified            BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT uq_product_canonical_name UNIQUE (canonical_name),
    CONSTRAINT chk_product_category CHECK (category IN
        ('STAPLE', 'DAIRY', 'PRODUCE', 'GRAIN', 'LEGUME', 'MEAT', 'FISH', 'BAKERY', 'CONDIMENT', 'FROZEN', 'OTHER')),
    CONSTRAINT chk_product_default_shelf_life_days_positive CHECK (default_shelf_life_days > 0),
    CONSTRAINT chk_product_grams_per_piece_positive CHECK (grams_per_piece IS NULL OR grams_per_piece > 0)
);

-- Synonyms for matching free-text/model input to an existing product before creating a new one (FR-43c).
CREATE TABLE product_synonym (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT       NOT NULL REFERENCES product (id),
    synonym    VARCHAR(150) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_product_synonym_lower ON product_synonym (lower(synonym));
CREATE INDEX idx_product_synonym_product_id ON product_synonym (product_id);
