-- Pantry stock (FR-20 to FR-29, INV-01, INV-02, NFR-43/NFR-43a).
-- user_id has no FK yet: the users table doesn't exist until the auth step (PRD 9.1 step 9),
-- which will add the FK in its own migration.
CREATE TABLE pantry_item (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT         NOT NULL,
    product_id     BIGINT         NOT NULL REFERENCES product (id),
    quantity       NUMERIC(10, 3) NOT NULL,
    unit           VARCHAR(20)    NOT NULL,
    purchased_at   DATE           NOT NULL,
    expires_at     DATE           NOT NULL,
    status         VARCHAR(20)    NOT NULL DEFAULT 'ACTIVE',
    discard_reason VARCHAR(30),
    version        INTEGER        NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),

    -- INV-01: pantry quantity can never be negative. This CHECK is the last line of defense (NFR-43);
    -- normal writes additionally rely on optimistic locking via `version` (NFR-43a).
    CONSTRAINT chk_pantry_item_quantity_non_negative CHECK (quantity >= 0),
    CONSTRAINT chk_pantry_item_unit CHECK (unit IN ('GRAM', 'MILLILITER', 'PIECE')),
    CONSTRAINT chk_pantry_item_status CHECK (status IN ('ACTIVE', 'CONSUMED', 'DISCARDED')),
    CONSTRAINT chk_pantry_item_discard_reason CHECK (discard_reason IN
        ('EXPIRED_EARLY', 'DIDNT_COOK_IN_TIME', 'BOUGHT_TOO_MUCH'))
);

CREATE INDEX idx_pantry_item_user_status ON pantry_item (user_id, status);
CREATE INDEX idx_pantry_item_product_id ON pantry_item (product_id);
CREATE INDEX idx_pantry_item_expires_at ON pantry_item (expires_at);
