-- Agent run and tool-call logs (PRD section 6, AI-30 to AI-35, PRD 4.6 state machine).
-- user_id has no FK yet: the users table doesn't exist until the auth step (PRD 9.1 step 9),
-- which will add the FK in its own migration.
CREATE TABLE agent_run (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT      NOT NULL,
    scenario              VARCHAR(50) NOT NULL,
    trigger               VARCHAR(50) NOT NULL,
    system_prompt_version VARCHAR(64) NOT NULL,
    status                VARCHAR(30) NOT NULL DEFAULT 'RUNNING',
    iteration_count       INTEGER     NOT NULL DEFAULT 0,
    error_message         TEXT,
    started_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at           TIMESTAMPTZ,

    -- Scenario set today has one member (PANTRY_ASSISTANT); more arrive with recipe
    -- generation (step 7) and shopping lists (step 10) — extend this list, don't widen it away.
    CONSTRAINT chk_agent_run_scenario CHECK (scenario IN ('PANTRY_ASSISTANT')),
    -- Status values mirror the terminal states in PRD section 4.6 exactly, plus RUNNING for
    -- an in-progress run and FINAL_RESPONSE for the normal successful completion.
    CONSTRAINT chk_agent_run_status CHECK (status IN
        ('RUNNING', 'FINAL_RESPONSE', 'TOOL_ERROR_FATAL', 'PERMISSION_DENIED',
         'VALIDATION_FAILED', 'ITERATION_LIMIT', 'LLM_TIMEOUT', 'BUDGET_EXCEEDED'))
);

CREATE INDEX idx_agent_run_user_id ON agent_run (user_id);

CREATE TABLE tool_call (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_run_id    BIGINT      NOT NULL REFERENCES agent_run (id),
    sequence_number INTEGER     NOT NULL,
    tool_name       VARCHAR(100) NOT NULL,
    arguments       TEXT        NOT NULL,
    result          TEXT,
    is_error        BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- AI-15: idempotency key is (agent run, sequence number) — this constraint is what makes
    -- "have we already applied this call" a lookup, not a convention.
    CONSTRAINT uq_tool_call_run_sequence UNIQUE (agent_run_id, sequence_number)
);

CREATE INDEX idx_tool_call_agent_run_id ON tool_call (agent_run_id);
