-- Generated recipes (PRD section 6, FR-34) and their ingredients (FR-31 scoring reads these
-- back against pantry stock). Only recipes that pass RecipeValidator (PRD step 5) are ever
-- persisted here — a recipe failing hard-constraint validation is discarded, not stored (AI-08).
-- user_id has no FK yet: the users table doesn't exist until the auth step (PRD 9.1 step 9).
CREATE TABLE recipe (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    name              VARCHAR(200) NOT NULL,
    cook_time_minutes INTEGER      NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT chk_recipe_cook_time_positive CHECK (cook_time_minutes > 0)
);

CREATE INDEX idx_recipe_user_id ON recipe (user_id);

-- Same @ElementCollection-backed join-table pattern as product_synonym (V2).
CREATE TABLE recipe_equipment (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT       NOT NULL REFERENCES recipe (id),
    equipment VARCHAR(100) NOT NULL
);

CREATE INDEX idx_recipe_equipment_recipe_id ON recipe_equipment (recipe_id);

CREATE TABLE recipe_ingredient (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id  BIGINT         NOT NULL REFERENCES recipe (id),
    product_id BIGINT         NOT NULL REFERENCES product (id),
    quantity   NUMERIC(10, 3) NOT NULL,
    unit       VARCHAR(20)    NOT NULL,

    CONSTRAINT chk_recipe_ingredient_quantity_positive CHECK (quantity > 0),
    CONSTRAINT chk_recipe_ingredient_unit CHECK (unit IN ('GRAM', 'MILLILITER', 'PIECE'))
);

CREATE INDEX idx_recipe_ingredient_recipe_id ON recipe_ingredient (recipe_id);
CREATE INDEX idx_recipe_ingredient_product_id ON recipe_ingredient (product_id);

-- New scenario (PRD 9.1 step 7): recipe generation and candidate scoring, alongside the
-- existing pantry-assistant scenario from step 6.
ALTER TABLE agent_run DROP CONSTRAINT chk_agent_run_scenario;
ALTER TABLE agent_run ADD CONSTRAINT chk_agent_run_scenario CHECK (scenario IN
    ('PANTRY_ASSISTANT', 'MEAL_PLANNING'));
