-- Step 8: cooking transaction, portion scaling, idempotency, cooked-dish inventory
-- (FR-52a-e, FR-53a/b, FR-54/54a, FR-56, FR-57, NFR-43b).

-- FR-53a's scaling coefficient is "actual portions / recipe portions" — the recipe needs to
-- state how many portions its ingredient list is written for.
ALTER TABLE recipe ADD COLUMN base_portions INTEGER NOT NULL DEFAULT 1;
ALTER TABLE recipe ADD CONSTRAINT chk_recipe_base_portions_positive CHECK (base_portions > 0);

-- FR-52a/FR-52e: shelf life by dish category, a categorical reference table seeded here rather
-- than computed or model-generated. SOUP exists for future refinement (FR-52e allows this) but
-- is not reachable by the v1 categorization rule (see DishCategoryResolver) — composition alone
-- doesn't reliably signal "soup".
CREATE TABLE dish_category_shelf_life (
    category        VARCHAR(20) PRIMARY KEY,
    shelf_life_days INTEGER NOT NULL,
    CONSTRAINT chk_dish_category_shelf_life_positive CHECK (shelf_life_days > 0)
);

INSERT INTO dish_category_shelf_life (category, shelf_life_days) VALUES
    ('FISH',        1),
    ('MEAT',        3),
    ('VEGETABLE',   3),
    ('GRAIN_PASTA', 3),
    ('SOUP',        4),
    ('UNKNOWN',     2);

-- FR-52b: cooked portions form a separate inventory, parallel to pantry_item, with the same
-- kind of operations (consume, expire, discard). FR-54/INV-05: nutrition per portion is
-- computed once at cooking time and frozen — never recomputed even if the product catalogue
-- changes later. FR-56/AI-15a: cooking confirmation is idempotent via an explicitly supplied
-- key, unlike the agent-run-scoped idempotency used elsewhere.
CREATE TABLE cooked_dish (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT         NOT NULL,
    recipe_id           BIGINT         NOT NULL REFERENCES recipe (id),
    category            VARCHAR(20)    NOT NULL REFERENCES dish_category_shelf_life (category),
    total_portions      NUMERIC(10, 3) NOT NULL,
    portions_remaining  NUMERIC(10, 3) NOT NULL,
    kcal_per_portion    NUMERIC(10, 2),
    protein_per_portion NUMERIC(10, 2),
    fat_per_portion     NUMERIC(10, 2),
    carbs_per_portion   NUMERIC(10, 2),
    cooked_at           DATE           NOT NULL,
    expires_at          DATE           NOT NULL,
    status              VARCHAR(20)    NOT NULL DEFAULT 'ACTIVE',
    idempotency_key     VARCHAR(200)   NOT NULL,
    version             INTEGER        NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT chk_cooked_dish_total_portions_positive CHECK (total_portions > 0),
    -- INV-09: eaten + remaining portions can never exceed the originally cooked amount —
    -- enforced here since remaining only ever decreases and is bounded by the total it started at.
    CONSTRAINT chk_cooked_dish_portions_remaining_range CHECK (
        portions_remaining >= 0 AND portions_remaining <= total_portions),
    CONSTRAINT chk_cooked_dish_status CHECK (status IN ('ACTIVE', 'CONSUMED', 'DISCARDED')),
    CONSTRAINT uq_cooked_dish_idempotency_key UNIQUE (idempotency_key)
);

CREATE INDEX idx_cooked_dish_user_status ON cooked_dish (user_id, status);
CREATE INDEX idx_cooked_dish_recipe_id ON cooked_dish (recipe_id);
