-- Step 9: authentication, invites (FR-01 to FR-05, NFR-12, NFR-20/20a).
--
-- Named app_user rather than PRD's "user": `user` is a reserved/special word in Postgres (a
-- pseudo-column/function), which would force quoting it everywhere. Same entity, friendlier name.
CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(320) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_app_user_email UNIQUE (email)
);

-- FR-01: one-time, tied to the account it registers. Stored in plaintext, unlike FR-80a's
-- hashed Telegram binding codes — an invite code isn't proving an existing identity the way a
-- binding code is, it's closer to a coupon; the PRD only asks for hashing on the Telegram side.
-- ON DELETE SET NULL, not CASCADE: an invite code is shared/system-issued infrastructure, not
-- part of the deleted user's own data (FR-05 shouldn't destroy it), so the row survives with
-- used_by_user_id cleared. isUsed() therefore checks used_at, not used_by_user_id — otherwise a
-- code would look unused again (and become reusable) the moment the user who consumed it is
-- deleted, silently reopening exactly what FR-01's one-time-use guarantee exists to prevent.
CREATE TABLE invite_code (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(64) NOT NULL,
    used_by_user_id BIGINT      REFERENCES app_user (id) ON DELETE SET NULL,
    used_at         TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_invite_code_code UNIQUE (code)
);

-- Dev-use codes. The PRD never specifies how codes are generated in production (no admin
-- endpoint requested) — this is the seed-migration treatment already used for product/dish
-- category reference data, applied here as a placeholder until that gap has an owner.
INSERT INTO invite_code (code) VALUES ('DEV-INVITE-0001'), ('DEV-INVITE-0002'), ('DEV-INVITE-0003');

-- Backfill the FK every earlier migration deferred to "the auth step" (see the comments in V3,
-- V5, V6). ON DELETE CASCADE makes FR-05 (cascading, irreversible account deletion) a single
-- `DELETE FROM app_user` — the database guarantees completeness of the cascade rather than
-- hand-written multi-table deletion code that has to be remembered as the schema grows.
ALTER TABLE pantry_item ADD CONSTRAINT fk_pantry_item_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE;
ALTER TABLE recipe ADD CONSTRAINT fk_recipe_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE;
ALTER TABLE agent_run ADD CONSTRAINT fk_agent_run_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE;
ALTER TABLE cooked_dish ADD CONSTRAINT fk_cooked_dish_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE;

-- tool_call has no user_id of its own — promote its existing FK to agent_run so that deleting
-- an agent_run (via the app_user cascade above) also removes its tool_call rows.
ALTER TABLE tool_call DROP CONSTRAINT tool_call_agent_run_id_fkey;
ALTER TABLE tool_call ADD CONSTRAINT tool_call_agent_run_id_fkey FOREIGN KEY (agent_run_id) REFERENCES agent_run (id) ON DELETE CASCADE;
