-- Step 10 Phase A: preferences, rejections, deterministic fallback (FR-24, FR-33, FR-60-63,
-- AI-20a/b/c).

-- FR-24: a suggestion's lifecycle. Only one row is ever ACTIVE per user at a time — creating a
-- new one expires whatever was previously ACTIVE (see RecipeSuggestionService.activate).
CREATE TABLE recipe_suggestion (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT         NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    recipe_id        BIGINT         NOT NULL REFERENCES recipe (id) ON DELETE CASCADE,
    status           VARCHAR(20)    NOT NULL DEFAULT 'ACTIVE',
    score            NUMERIC(6, 4)  NOT NULL,
    rejection_reason VARCHAR(30),
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    resolved_at      TIMESTAMPTZ,

    CONSTRAINT chk_recipe_suggestion_status CHECK (status IN ('ACTIVE', 'ACCEPTED', 'REJECTED', 'EXPIRED')),
    -- NOT_TODAY is a valid reason to record here (FR-62 only excludes it from the long-term
    -- preference_signal below, not from this per-suggestion record).
    CONSTRAINT chk_recipe_suggestion_rejection_reason CHECK (rejection_reason IN
        ('DISLIKE_DISH', 'NOT_TODAY', 'TAKES_TOO_LONG', 'DONT_WANT_CATEGORY', 'TIRED_OF_INGREDIENT'))
);

CREATE INDEX idx_recipe_suggestion_user_status ON recipe_suggestion (user_id, status);

-- FR-60/FR-63: soft signal, matched by recipe name (Phase A simplification — see plan notes).
-- recipe_name is denormalized from recipe.name at write time so the scorer's hot-path lookup
-- doesn't need a join.
CREATE TABLE preference_signal (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT         NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    recipe_id   BIGINT         NOT NULL REFERENCES recipe (id) ON DELETE CASCADE,
    recipe_name VARCHAR(200)   NOT NULL,
    reason      VARCHAR(30)    NOT NULL,
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),

    -- NOT_TODAY intentionally excluded (FR-62): it never affects the long-term preference model.
    CONSTRAINT chk_preference_signal_reason CHECK (reason IN
        ('DISLIKE_DISH', 'TAKES_TOO_LONG', 'DONT_WANT_CATEGORY', 'TIRED_OF_INGREDIENT'))
);

CREATE INDEX idx_preference_signal_user ON preference_signal (user_id);

-- AI-20a: the meal-planning scenario's deterministic fallback when the iteration limit is hit.
ALTER TABLE agent_run DROP CONSTRAINT chk_agent_run_status;
ALTER TABLE agent_run ADD CONSTRAINT chk_agent_run_status CHECK (status IN
    ('RUNNING', 'FINAL_RESPONSE', 'TOOL_ERROR_FATAL', 'PERMISSION_DENIED',
     'VALIDATION_FAILED', 'ITERATION_LIMIT', 'LLM_TIMEOUT', 'BUDGET_EXCEEDED', 'FALLBACK_RESPONSE'));
